version: '3'
services:
  app:
    build: ./app/.devcontainer
    volumes: 
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    links:
      - func
    ports:
      - 4280:4280
  func:
    build: ./func/.devcontainer
    volumes: 
    - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - 7071:7071
    links:
      - azurite
  azurite:
    image: "mcr.microsoft.com/azure-storage/azurite"
    ports:
        - "10000:10000"
        - "10001:10001"
        - "10002:10002"